

Modes:
    - mode : normal
      preset : normal_1

    - mode: soirée
      preset: soirée_1

Interrupts:
    config : |
        | name    | type     | args |

Variables:
    config : |
        | name      | value |


Objects:
    config : |
        | name           | type     | sub_type | relay/triak    | addr          |
        | projo_28       | dimmable | buld_200 | 2(2)           |               |
        | projo_30       | dimmable | buld_200 | 1(2)           |               |
        | projo_33       | dimmable | buld_91  | 3(1)           |               |
        | projo_34       | dimmable | buld_91  | 4(1)           |               |
        | projo_35       | dimmable | buld_91  | 6(1)           |               |
        | projo_46       | dimmable | buld_91  | 6(5)           |               |
        | led_mur_gauche | led      | dmx      | 5(1)           | 406           |
        | led_mur_centre | led      | dmx      | 5(1)           | 400           |
        | led_mur_droite | led      | dmx      | 5(1)           | 403           |
        | led_sous_table | led      | lednet   | 13(pi_salle.1) | 192.168.1.108 |
