ME: pi_test

MODES:
    - name: normal
      html:
          - name: home.test1.but_test2
            type: button
            background_image: sun.png
            inactive_color: black
            active_color: grey

    - name: soirée
      html:
          - name: home.test1.mode2
            type: button
            background_image: night.png
            inactive_color: black
            active_color: grey

                       
        




