ME: appart

MODES:
    - name: normal


BOARDS:
    # ST_nucleos and port_extender boards
    # the interrupts and boards with GPIO pins or network are listed
    # directly in the config objects or interrupt
    ST_nucleos:
        # configure all board here
        - name : ST_nucleo_1
          addr : /dev/ttyACM0
          triak_boards :
              # index is the index when the board is called in connected objects config
              - index,nb_triak : 1,8 
              - index,nb_triak : 2,8 
              - index,nb_triak : 3,8 
