

Modes:
    - mode : normal
      preset : normal_1

    - mode: soirée
      preset: soirée_1

Interrupts:
    config : |
        | name    | type     | args |

Variables:
    config : |
        | name    | value |
        | pan_1   | 0     |
        | pan_2   | 0     |
        | tilt    | 0     |
        | couleur | 0     |
        | gobo    | 0     |


Objects:
    config : |
        | name  | type    | sub_type | relay/triak | addr |
        | boule | crazy_2 |          | 6(1)        | 52   |

