

Modes:

    - mode : jour
      preset : jour
      marker: ON

    - mode : nuit
      preset : nuit
      marker: OFF


Interrupts:
    config : |
        | name         | type | args |

Variables:
    config : |
        | name        | value |


Objects:
    config : |
        | name | type | sub_type | relay/triak | addr |
        | vmc  | lamp |          | 20(gpio)    |      |

