

Modes:
    - mode : normal
      preset : normal_1

    - mode : cinema
      preset : normal_1

    - mode : soirée
      preset : soirée_1


Interrupts:
    config : |
        | name    | type     | args |

Variables:
    config : |
        | name        | value |


Objects:
    config : |
        | name          | type     | sub_type | relay/triak | addr |
        | projo_couloir | dimmable | buld_200 | 8(1)        |      |

