

Modes:
    - mode : normal
      preset : normal_1

    - mode: soirée
      preset: soirée_1


Interrupts:
    config : |
        | name      | type     | args  |
        | inter_4   | extender | 4     |

Variables:
    config : |
        | name      | value |


Objects:
    config : |
        | name   | type     | sub_type | relay/triak | addr |
        | poutre | dimmable | buld_73  | 5(2)        |      |

