

Modes:
    - mode : normal
      preset : normal_1

    - mode: soirée
      preset: soirée_1

Interrupts:
    config : |
        | name    | type     | args |
        | inter_3 | extender | 3    |
        | inter_9 | extender | 9    |
        | inter_16 | extender | 16    |

Variables:
    config : |
        | name      | value |


Objects:
    config : |
        | name     | type     | sub_type | relay/triak | addr |
        | projo_27 | dimmable | buld_61  | 3(2)        |      |
        | projo_31 | dimmable | buld_91  | 8(1)        |      |
        | projo_32 | dimmable | buld_91  | 2(1)        |      |
        | poutre   | dimmable | buld_91  | 1(1)        |      |

