

Modes:
    - mode : normal
      preset : normal_1

    - mode: soirée
      preset: soirée_1

Interrupts:
    config : |
        | name     | type     | args |
        | inter_3  | extender | 3    |
        | inter_9  | extender | 9    | # there are an issue on the pin 16 (port extender 0x20,0 pin 8)
        | inter_16 | extender | 19   | # it just blink when we dim a light. solve : link 2 cables, remove pin 16
        

Variables:
    config : |
        | name      | value |


Objects:
    config : |
        | name     | type     | sub_type | relay/triak | addr |
        | projo_27 | dimmable | buld_200 | 3(2)        |      |
        | projo_31 | dimmable | buld_91  | 8(1)        |      |
        | projo_32 | dimmable | buld_91  | 2(1)        |      |
        | projo_36 | dimmable | buld_91  | 7(1)        |      |
        | poutre   | dimmable | buld_91  | 1(1)        |      |

