

Modes:

    - mode : jour
      preset : jour

Interrupts:
    config : |
        | name                   | type | args |
        | inter_cuisine          | gpio | 25   |
        | inter_couloir2         | gpio | 19   |

Objects:
    config : |
        | name        | type      | sub_type | relay/triak | addr              |
        | panneau_led | led_panel | dmx      | 16(gpio)    | 1                 |
        | led_evier   | led       | bledom   | 14(gpio)    | be:ff:40:00:f0:60 |

