

Modes:
    - mode : normal
      preset : normal_1

Interrupts:
    config : |
        | name    | type     | args |

Variables:
    config : |
        | name             | value |
        | volume_exterieur | 0     |


Objects:
    config : |
        | name               | type     | sub_type | relay/triak      | addr |
        | enceinte_exterieur | speakers |          | 3(ampli_6_zones) |      |

