

Modes:
    - mode : normal
      preset : normal_1

    - mode : cinema
      preset : normal_1

    - mode : soirée
      preset : soirée_1

Interrupts:
    config : |
        | name    | type     | args |
        | inter_1 | extender | 1      |

Variables:
    config : |
        | name        | value |


Objects:
    config : |
        | name | type | sub_type | relay/triak | addr |
        | vmc  | lamp |          | 13(2)       |      |

