

Modes:
    - mode : normal
      preset : normal_1

    - mode : soirée
      preset : soirée_1

Interrupts:
    config : |
        | name     | type     | args |
        | inter_18 | extender | 18   |

Variables:
    config : |
        | name      | value |


Objects:
    config : |
        | name     | type     | sub_type | relay/triak | addr |
        | projo_24 | dimmable | buld_65  | 8(2)        |      |
        | projo_26 | dimmable | buld_91  | 4(2)        |      |
        | projo_47 | dimmable | buld_91  | 7(5)        |      |

