

Modes:
    - mode : normal
      preset : normal_1

Interrupts:
    config : |
        | name      | type     | args   |
        | inter_16  | extender | 16     |
        | inter_17  | extender | 17     |
        | inter_5   | extender | 5      |
        | power_amp | network  | pi_son |

Variables:
    config : |
        | name           | value |
        | volume_general | 28    |


Objects:
    config : |
        | name     | type     | sub_type | relay/triak      | addr |

