

Modes:
    - mode : normal
      preset : normal_1

Interrupts:
    config : |
        | name     | type     | args |
        | inter_15 | extender | 15   |
        | inter_17 | extender | 17   |

Variables:
    config : |
        | name      | value |


Objects:
    config : |
        | name     | type     | sub_type | relay/triak      | addr |

