

Modes:
    - mode : normal
      preset : normal_1

    - mode : soirée
      preset : soirée_1

    - mode : cinema
      preset : cinema_1

    - mode : soirée_calme
      preset : soirée_calme

Interrupts:
    config : |
        | name               | type     | args |
        | inter_couloir      | extender | 4    |
        | inter_regie_droite | extender | 3    |
        | inter_7            | extender | 7    |
        | bas_porte          | extender | 2    |

Variables:
    config : |
        | name        | value |


Objects:
    config : |
        | name | type | sub_type | relay/triak | addr |

