

Modes:
    - mode : normal
      preset : normal_1

    - mode: soirée
      preset: soirée_1

Interrupts:
    config : |
        | name    | type     | args |
        | inter_7 | extender | 7    |

Variables:
    config : |
        | name           | value |
        | color_index    | 0     |
        | color1         | 0     |
        | color2         | 0     |
        | dimmer_general | 100   |


Objects:
    config : |
        | name         | type     | sub_type  | relay/triak | addr      |

