

Modes:
    - mode : normal
      preset : normal_1

Interrupts:
    config : |
        | name          | type | args |
        | inter_general | gpio | 5   |

Variables:
    config : |
        | name        | value |


Objects:
    config : |
        | name         | type     | sub_type  | relay/triak | addr      |

