

Modes:
    - mode : normal
      preset : normal_1

Interrupts:
    config : |
        | name           | type    | args      |
        | change_spotify | network | pi_maison |

Variables:
    config : |
        | name           | value |


Objects:
    config : |
        | name         | type     | sub_type  | relay/triak | addr      |

