

Modes:
    - mode : normal
      preset : normal_1

    - mode : cinema
      preset : cinema_1

    - mode : soirée
      preset : soirée_1

    - mode : soirée_calme
      preset : soirée_calme


Interrupts:
    config : |
        | name    | type     | args   |

Variables:
    config : |
        | name        | value |


Objects:
    config : |
        | name          | type     | sub_type | relay/triak | addr |
        | projo_1       | dimmable | buld_200 | 1(1)        |      |
        | projo_2       | dimmable | buld_200 | 2(1)        |      |
        | projos_bois   | dimmable | buld_200 | 5(1)        |      |
        | projos_pierre | dimmable | buld_200 | 6(1)        |      |

