

Modes:
    - mode : normal
      preset : normal_1

    - mode: soirée
      preset: soirée_1

Interrupts:
    config : |
        | name    | type     | args |
        | inter_10 | extender | 10    |

Variables:
    config : |
        | name      | value |


Objects:
    config : |
        | name        | type     | sub_type | relay/triak | addr              |
        | poutre      | dimmable | buld_91  | 4(3)        |                   |
        | projo_37    | dimmable | buld_91  | 3(3)        |                   |
        | projo_38    | dimmable | buld_91  | 5(5)        |                   |
        | projo_39    | dimmable | buld_63  | 7(4)        |                   |
        | projo_40    | dimmable | buld_63  | 8(4)        |                   |
        | led_caisson | led      | lednet   | 6(1)        | 10.0.0.55         |
        | led_sol     | led      | bledom   | 6(1)        | be:89:20:00:23:3d |
        | decoupe     | dimmable | dmx      | 16(1)       | 500               |

